### ISSUE TITLE
Node 16 Update Required By June 14th

### ISSUE THREAD

**Issue by mccarron** [uesteibar/reviewer-lottery#39]
Github [is turning off Node 12 support and Actions need to be updated to Node 16 by June 14th](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/). If not updated, this action will stop working.

This is the current issue returned to us when this runs: 

> assign_reviewers
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: uesteibar/reviewer-lottery@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Sorry it was not raised sooner, this one slipped through our cracks with others that we were dealing with.

**Comment by uesteibar** [comment]
Done and published as v3, thanks for the heads up!

**Comment by mccarron** [comment]
@uesteibar You're amazing. Thanks so much, updating this week!
